/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tiendalibro;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe Perdomo http://commander-java.blogspot.mx/
 * @version Raúl García Cortés | GarciaCortes.Raul@gmail.com | http://javaeditados.wordpress.com/
 * 
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de Biblioteca en Java - Por Raúl GC");
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonComprar = new javax.swing.JToggleButton();
        BotonPrestar = new javax.swing.JToggleButton();
        BotonSalir = new javax.swing.JButton();
        EtiquetaTitulo = new javax.swing.JLabel();
        EtiquetaFondo = new javax.swing.JLabel();
        BarraMenu = new javax.swing.JMenuBar();
        MenuBiblioteca = new javax.swing.JMenu();
        About = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("FramePrincipal"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonComprar.setText("Comprar Libros");
        BotonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonComprarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 204, 33));

        BotonPrestar.setText("Prestar Libros");
        BotonPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPrestarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonPrestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 204, 33));

        BotonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiendalibro/cancelar.png"))); // NOI18N
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 60, 50));

        EtiquetaTitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        EtiquetaTitulo.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaTitulo.setText("Bliblioteca escolar");
        getContentPane().add(EtiquetaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 290, -1));

        EtiquetaFondo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        EtiquetaFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiendalibro/427167_biblioteka_polki_knigi_noutbuk_list_bumaga_ruchka__1680x1050_(www.GdeFon.ru)-001.jpg"))); // NOI18N
        getContentPane().add(EtiquetaFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MenuBiblioteca.setText("Biblioteca");

        About.setText("Acerca de...");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });
        MenuBiblioteca.add(About);

        Exit.setText("Salir");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        MenuBiblioteca.add(Exit);

        BarraMenu.add(MenuBiblioteca);

        setJMenuBar(BarraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPrestarActionPerformed

        Prestamo.main(null);
    
    }//GEN-LAST:event_BotonPrestarActionPerformed

    private void BotonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonComprarActionPerformed
       
        
       
 
        Venta.main(null);
    }//GEN-LAST:event_BotonComprarActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
      
        dispose();
        try {
                try {
                    Desktop.getDesktop().browse(new URI("http://JavaEditados.wordpress.com/"));
                } catch (IOException ex) { }
            } catch (URISyntaxException ex) { }
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        try {
                try {
                    Desktop.getDesktop().browse(new URI("http://JavaEditados.wordpress.com/"));
                } catch (IOException ex) { }
            } catch (URISyntaxException ex) { }
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,""
                    + "Sistema de Bibliotecas\n"
                    + "Préstamos y Ventas de Libros\n"
                    + "\tAutor: Felipe Perdomo (Artyom Commander)\n"
                    + "\tEditado por: Raúl García Cortés\n"
                    + "\tPara: http://JavaEditados.wordpress.com/\n"
                    + "");
        try {
                try {
                    Desktop.getDesktop().browse(new URI("http://JavaEditados.wordpress.com/"));
                } catch (IOException ex) { }
            } catch (URISyntaxException ex) { }
    }//GEN-LAST:event_AboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JToggleButton BotonComprar;
    private javax.swing.JToggleButton BotonPrestar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JLabel EtiquetaFondo;
    private javax.swing.JLabel EtiquetaTitulo;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu MenuBiblioteca;
    // End of variables declaration//GEN-END:variables
}
